server:
  port: 8080
application:
  name: ttrack-service

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    observation:
      enabled: true
logging:
  file:
    name: ttrack-service.log
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,logfile,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      logging:
        enabled: true
        step: 30s
      azuremonitor:
        enabled: ${AZURE_MONITOR_ENABLED:false}
        # set via environment or secrets when available
        connection-string: ${AZURE_MONITOR_CONNECTION_STRING:}
azure:
  tables:
    endpoint: https://shavitttrackwestus.table.core.windows.net/
  blobs:
    endpoint: https://shavitttrackwestus.blob.core.windows.net/

service:
  cache:
    directory: /tmp/ttrack-service/cache